export enum ApiMessageTypes {
  INTERNAL_SERVER_ERROR = "Internal Server Error",
  CUSTOMER_CREATED_SUCCESSFULLY = "Customer created successfully",
  CUSTOMER_DELETED_SUCCESSFULLY = "Customer deleted successfully",
  CUSTOMER_NOT_CREATED = "Customer could not be created",
  NO_ROOMS_AVAILABLE = "No rooms available for the selected dates",
  UNABLE_TO_DELETE_CUSTOMER = "Unable to delete customer",
  CUSTOMER_DOES_NOT_EXIST = "Customer does not exist",
  INVALID_OPERATION_TYPE = "Invalid operation type",
  NO_BOOKING_FOUND = "No booking found",
  SESSION_TIMEOUT = "Session has timed out",
  UNAUTHORIZED_ACCESS = "Unauthorized access",
  NOT_FOUND = "Resource not found",
  BAD_REQUEST = "Bad request",
  DUPLICATE_ENTITY = "Duplicate entity",
  ENTITY_NOT_AVAILABLE = "Entity not available",
  BOOKING_NOT_CONFIRMED = "Booking could not be confirmed",
  BOOKING_CANCEL_FAILED = "Booking cancellation failed",
}
