export enum ApiErrorCodesEnum {
  SESSION_TIMEOUT = "SESSION_TIMEOUT",
  UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  DUPLICATE_ENTITY = "DUPLICATE_ENTITY",
  ENTITY_NOT_AVAILABLE = "ENTITY_NOT_AVAILABLE",
}
